{{- if and .Values.httpRoute.enabled .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpRoute.name }}
  labels:
    {{- include "resume-api.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
  {{- range .Values.httpRoute.hostnames }}
    - {{ . | quote }}
  {{- end }}
  rules:
  {{- range .Values.httpRoute.rules }}
    - matches:
    {{- range .matches }}
      - path:
          type: {{ .path.type }}
          value: {{ .path.value }}
    {{- end }}
      backendRefs:
      {{- range .backendRefs }}
      - name: {{ include "resume-api.fullname" $ }}
        port: {{ .port }}
      {{- end }}
  {{- end }}
{{- end }}
