{{- if and .Values.database.external.enabled (not .Values.database.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resume-api.fullname" . }}-db-credentials
  labels:
    {{- include "resume-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.external.existingSecretPasswordKey }}: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
